### ISSUE TITLE
Inject styles object as a property

### ISSUE THREAD

**Issue by gajus** [gajus/react-css-modules#11]
There is a case where React CSS Modules cannot map `styleName` to a CSS Module automatically:

```js
class extends React.Component {
    render () {
        return <List itemTemplate={() => {
            return <li styleName='foo' />
        }} />
    }
}
```

Thank you to @vjeux for bringing this to my attention.

I think that the most elegant solution would be to inject `styles` property for the edge cases such as this. Then the latter component can be implemented using `this.props.styles` property, e.g.

```js
class extends React.Component {
    render () {
        return <List itemTemplate={() => {
            return <li styleName={this.props.styles.foo} />
        }} />
    }
}
```

Furthermore, I could use [`camelcase`](https://www.npmjs.com/package/camelcase) package to map dash names to underscore.

I'd like to know whats everyones thoughts about this.

**Comment by gajus** [comment]
Keeping this unresolved until someone actually runs into this deficiency.

**Comment by jrunning** [comment]
I've run into a few scenarios where someone else's component accepts a CSS class name as a prop, e.g. Griddle has `gridClassName`, `tableClassName`, `sortAscendingClassName` etc. props, in which case I've found it useful to simply do:

```js
<Griddle gridClassName={styles['custom-grid']} tableClassName={styles['custom-table']} ... />
```

...since I already have `styles` in scope. I think if I ran into a situation like your example above I would be fine doing the same:

```js
render() {
  return <List itemTemplate={() => {
    return <li className={styles.foo} />;
  }} />;
}

**Comment by channikhabra** [comment]
I think I am facing the same issue.

When some time we have to pass components to another component as a prop, it don't carry proper style names. e.g

```js
<Carousel
              items={items.map((date) => <span key={item.id}>
                   <span styleName={name}>{name}</span>
              </span>)}  />
.
.
.
export default CSSModules(MyComponent, styles);
```

In this case, react-css-modules expect `Carousel` to provide `name` style and fails since it don't. It's obvious that this fails since we apply `react-css-modules` as a higher-order-component later in code.

I worked around this by doing:

```js
<Carousel
              items={items.map((date) => <span key={item.id}>
                   <span className={styles.name}>{name}</span>
              </span>)}  />
.
.
.
export default CSSModules(MyComponent, styles);
```

Don't know if it's solvable or if it's a problem at all. Just letting you know the use-case.

**Comment by gajus** [comment]
@channikhabra This is going produce unexpected behaviour when/if user overwrites the default styles (https://github.com/gajus/react-css-modules#extending-component-styles).

**Comment by gajus** [comment]
This has been solved using `styles` properly. https://github.com/gajus/react-css-modules#styles-property

**Comment by otbe** [comment]
Mh, this is a real deal breaker for us.

Something like https://github.com/gajus/react-css-modules/issues/29 should be really possible... :(

**Comment by gajus** [comment]
@otbe It has been discussed at length. This is an issue/bug/deficiency in any way.

CSS Modules scope is limited to the primary DOM generated by a React component. Whatever descendants (including dynamically generated nodes within the component itself) must either use `styles` property or be decorated with `react-css-modules`.

**Comment by texttechne** [comment]
> This is not an issue/bug/deficiency in any way.

@gajus I would like to contradict, because this limitation of the `styleName` property is neither intuitive  (#29 speaks for itself in this regard) nor does it allow for a consistent usage. 

At some point I'm forced to switch to the `styles` property and this is a big issue. I'm left with two paradigms of using CSS classes in my react components. Simple refactorings can become tedious (switching from `styleName` to `styles` and vice versa?) and this does not scale well in bigger teams (imagine you would need to explain this 'rule'). 

Actually this limitation undermines your project: Instead of the `styles` property I can use the imported styles from css-modules (see [third comment](#issuecomment-141219155)) and *not use react-css-modules* at all, which is more convient in these cases (`this.props.styles` vs. `styles`).

So much for my argument. I don't want to offend and I like your solution, but please reconsider if you could improve this library to allow for intuitive and consistent usage.

**Comment by gajus** [comment]
It just occurred to me that the workaround for this is super simple.

Here is a simple `CustomList` component:

```js
import React from 'react';
import CSSModules from 'react-css-modules';
import List from './List';
import styles from './table.css';

let CustomList;

CustomList = class extends React.Component {
    render () {
        let itemTemplate;

        itemTemplate = (name) => {
            return <li className={this.props.styles['item-template']}>{name}</li>;
        };

        return <List itemTemplate={name} />;
    }
}

export default CSSModules(CustomList, styles);
```

The reason we are using `this.props.styles` and not `styleName` in the `itemTemplate` is simply because `itemTemplate` is itself another component (stateless component) and since we are decorating only the `render` method `CustomList`, there is no way to access `styleName` property at the time of the render.

The solution is simple: decorate the `itemTemplate` component.

```js
import React from 'react';
import CSSModules from 'react-css-modules';
import List from './List';
import styles from './table.css';

let CustomList;

CustomList = class extends React.Component {
    render () {
        let itemTemplate;

        itemTemplate = (name) => {
            return <li styleName='item-template'>{name}</li>;
        };

        itemTemplate = CSSModules(itemTemplate, this.props.styles);

        return <List itemTemplate={name} />;
    }
}

export default CSSModules(CustomList, styles);
```

Simple.

**Comment by gajus** [comment]
Updated docs to include this example https://github.com/gajus/react-css-modules#loops-and-child-components.

**Comment by texttechne** [comment]
Yep, it's super simple. Not sure about the perf impact there, but solves the issue for both approaches.

Thanks for clarification and especially the doc update.
