### ISSUE TITLE
Overriding CSS Libraries?

### ISSUE THREAD

**Issue by dijs** [gajus/react-css-modules#21]
I am running into an issue when trying to use this with Material UI. Since Material UI uses inline styles, those styles override the classes generated by react-css-modules.

Any ideas how to workaround this issue?

**Comment by gajus** [comment]
This issue has more to do with Material UI than react-css-modules. Unfortunately, I am not familiar with Material UI enough to suggest a possible workaround. I will leave the issue open in case other people stumble upon it with broader exposure to both libraries.

In the mean time, please open an issue with Material UI and mention me. I will contribute to the conversation whatever I can.

**Comment by dijs** [comment]
Thank you, I definitely agree with you. Just was hoping for some insight from other developers.

**Comment by chapati23** [comment]
facing the exact same issue. for now we went the ugly route and override material-ui styles with !important.

you could ditch the important by explicitly nulling material-ui's styles but that doesn't make it any prettier IMO => https://github.com/callemall/material-ui/issues/760

@gajus there's no way to access the actual styles-object in the component, right?
just thinking because we already `import styles from './styles.css'` we already have the raw-text in there. probably way out of scope but technically you should be able to extract the style-definitions, create an inline-styles object and then override the material components with that object.

IMO inline-styles are a terrible choice when writing a framework where you want high extensibility and customisability and there's lots of discussion in the material forum about new approaches
