### ISSUE TITLE
How does using react-css-modules affect the shareable components story?

### ISSUE THREAD

**Issue by adamdicarlo** [gajus/react-css-modules#27]
How easy would it be to use someone else's component built with ReactCSSModules?

(This gets into the larger/more general issue of using shared components, of course—this could be out of scope here, but this is something I think about a lot :smiley:)

For example, a component published to npm (public or private registry). Would consumers need to use the component's "dist" (compiled down) version (which could lead to duplication of packages in your final bundle, if your component uses, e.g. Lodash, and so does my app)? Would they be able to import your JS directly... and if they did would they have to use the ReactCSSModules plugin? If so there might need to be an option for the plugin to only autoload scss/css for deps in node_modules or some such...?

Or maybe there's some special webpack magic that allows declaring loaders config in your package.json that webpack will respect? (And the host app maybe needs to install react-css-modules as a devDep, but that would be not too bad...)

**Comment by ahdinosaur** [comment]
> Or maybe there's some special webpack magic that allows declaring loaders config in your package.json that webpack will respect? (And the host app maybe needs to install react-css-modules as a devDep, but that would be not too bad...)

afaik, the current architecture of webpack is such that loaders are only global. i reckon you should try [browserify](http://browserify.org), which is [based on local transforms instead of global loaders](https://gist.github.com/substack/68f8d502be42d5cd4942#transforms-instead-of-loaders), written for the purpose of sharing browser modules. :smile:

**Comment by adamdicarlo** [comment]
@ahdinosaur Would you recommend/have you tried mixing Webpack and Browserify? I've been *extremely* happy with Webpack at the *application* level. I'm not sure if you're suggesting Browserify all the way or some (awesome? disturbing? hilarious?) combination of the two. :grin:

**Comment by ahdinosaur** [comment]
@adamdicarlo i've only used one or the other: for my own projects i use browserify all the way since it works really well, is simple modular and pluggable, has a vibrant ecosystem around it, retains the same design principles as node, and is used by most open source module publishers who i collaborate with; for projects with others i've used webpack because hot-reloading ([also possible with browserify](https://github.com/AgentME/browserify-hmr)) or something.

it's possible to support both while only using one yourself (think universal module loader but for module bundlers), but again i'm not sure how to achieve modularity with webpack's current architecture of global loaders. i can't imagine it's not been thought of, so hopefully someone else can chime in here with how to do local per-module loading with webpack.

**Comment by gajus** [comment]
> afaik, the current architecture of webpack is such that loaders are only global.

That is nonsense.

@adamdicarlo the generated output of webpack and browserify are equivalent.

`react-css-modules` allow to overwrite CSS modules at the program using a decorated component level (https://github.com/gajus/react-css-modules#extending-component-styles). Therefore, you do not need to rebuild the component with specific styles.

The top most bundler (regardless of if it is webpack, browserify or another alternative) will need to support CSS modules to either inline the resolved CSS in the actual build used to render the contents or write them into a separate file(s) as in the case of the https://github.com/gajus/react-css-modules-examples.

**Comment by gajus** [comment]
`react-css-modules` enable re-usable components with re-usable/overwritable CSS module declarations.

**Comment by ahdinosaur** [comment]
> The top most bundler (regardless of if it is webpack, browserify or another alternative) will need to support CSS modules to either inline the resolved CSS in the actual build used to render the contents or write them into a separate file(s) as in the case of the https://github.com/gajus/react-css-modules-examples.

oh wow somehow i assumed [`css-modulesify`](https://github.com/css-modules/css-modulesify) was a browserify transform, but it's a plugin, which is indeed global as you say.

re-reading my response to the question, thanks @gajus for more aptly responding to the actual question of whether `react-css-modules` supports re-usable components, sorry for going on a tangent about webpack vs browserify.
