### ISSUE TITLE
Problem of Extending Component Styles

### ISSUE THREAD

**Issue by chenxsan** [gajus/react-css-modules#34]
Setup a demo [here](https://github.com/chenxsan/react-css-modules-demo).

Say I want to extend [App style](https://github.com/chenxsan/react-css-modules-demo/blob/master/src/App.css) with [extend.css](https://github.com/chenxsan/react-css-modules-demo/blob/master/src/extend.css), I only want to overwrite the `.title` className, and keep the `.footer` defined in App.css.

react-css-modules would throw:

<img width="1264" alt="screen shot 2015-09-24 at 11 54 22" src="https://cloud.githubusercontent.com/assets/1091472/10065083/2286b2b6-62b3-11e5-9b8c-32ed24195ce4.png">

Seems like if I want to extends my component's styles, I need to redefined all the classNames in the default css file again, or I would get '...CSS Module is undefined' error.

**Comment by gajus** [comment]
This is by design. It is not up to react-css-modules to manage how CSS module inherit classes from another CSS module. It is up to the Interoperable CSS format to implement methods for inheritance. Therefore, this issue is more appropriate with https://github.com/css-modules/icss.

Mention me if you are writing a spec proposal.

**Comment by clessg** [comment]
:+1: This is quite a pain. Hope there will be a solution on this front.
